-- MySQL Script generated by MySQL Workbench
-- Wed Jul 25 20:41:30 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema workshop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema workshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `workshop` DEFAULT CHARACTER SET utf8 ;
USE `workshop` ;

-- -----------------------------------------------------
-- Table `workshop`.`vehicle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workshop`.`vehicle` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `model` VARCHAR(30) NULL,
  `brand` VARCHAR(30) NULL,
  `year_of_production` YEAR NULL,
  `license_plate` CHAR(7) NULL,
  `next_inspection` DATE NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `license_plate_UNIQUE` (`license_plate` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `workshop`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workshop`.`employee` (
  `id` INT UNSIGNED auto_increment,
  `name` VARCHAR(50) NULL,
  `last_name` VARCHAR(80) NULL,
  `address` VARCHAR(150) NULL,
  `phone` CHAR(9) NULL,
  `note` TEXT NULL,
  `man_hour` DECIMAL(5,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `workshop`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workshop`.`customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL,
  `last_name` VARCHAR(80) NULL,
  `date_of_birth` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `workshop`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workshop`.`order` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `date_of_accepting` DATETIME NULL,
  `planned_start_date` DATE NULL,
  `end_date` DATE NULL,
  `description_of_the_problem` TEXT NULL,
  `repair_description` TEXT NULL,
  `status` ENUM('Przyjęty', 'Zatwierdzone koszty naprawy', 'W naprawie', 'Gotowy do odbioru', 'Rezygnacja') NULL,
  `repair_cost` DECIMAL(7,2) NULL,
  `part_cost` DECIMAL(7,2) NULL,
  `man_hours` INT NULL,
  `vehicle_id` INT UNSIGNED NOT NULL,
  `customer_id` INT NOT NULL,
  `employee_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_vehicle_idx` (`vehicle_id` ASC),
  INDEX `fk_order_customer1_idx` (`customer_id` ASC),
  INDEX `fk_order_employee1_idx` (`employee_id` ASC),
  CONSTRAINT `fk_order_vehicle`
    FOREIGN KEY (`vehicle_id`)
    REFERENCES `workshop`.`vehicle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `workshop`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `workshop`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `workshop` ;

-- -----------------------------------------------------
-- Placeholder table for view `workshop`.`vOrder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workshop`.`vOrder` (`id` INT, `date_of_accepting` INT, `planned_start_date` INT, `end_date` INT, `description_of_the_problem` INT, `repair_description` INT, `status` INT, `repair_cost` INT, `part_cost` INT, `man_hours` INT, `cost_for_hours` INT, `employee_id` INT, `employee` INT, `customer_id` INT, `customer` INT, `vehicle_id` INT, `vehicle` INT);

-- -----------------------------------------------------
-- View `workshop`.`vOrder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `workshop`.`vOrder`;
USE `workshop`;
CREATE  OR REPLACE VIEW `vOrder` AS
    SELECT 
        `order`.id,
        `order`.date_of_accepting,
        `order`.planned_start_date,
        `order`.end_date,
        `order`.description_of_the_problem,
        `order`.repair_description,
        `order`.`status`,
        `order`.repair_cost,
        `order`.part_cost,
        `order`.man_hours,
        SUM(employee.man_hour * `order`.man_hours) AS cost_for_hours,
        `order`.employee_id,
        employee.`name` + ' ' + employee.last_name AS employee,
        `order`.customer_id,
        customer.`name` + ' ' + customer.last_name AS customer,
        `order`.vehicle_id,
        vehicle.brand + ' ' + vehicle.model + ' ' + vehicle.year_of_production + ' ' + ' ' + license_plate AS vehicle
    FROM
        `order`
            JOIN
        vehicle ON `order`.vehicle_id = vehicle.id
            JOIN
        customer ON `order`.customer_id = customer.id
            JOIN
        employee ON `order`.employee_id = employee.id;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
